# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Nexus Engine contributors
# Minimal Python lint config — used by future scripts/sdks-py.

target-version = "py312"
line-length = 100

[lint]
select = ["E", "F", "I", "B", "UP", "RUF"]
ignore = []

[lint.per-file-ignores]
"tests/*" = ["B011"]
"**/__init__.py" = ["F401"]
